import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations"
import { dark } from "@clerk/themes";
import { ConfettiProvider } from "@/providers/confetti-provider";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sonhos e Conquistas!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR} appearance={{baseTheme: dark}}>
      <html lang="en">
        <body className={dmSans.className}>
          <ConfettiProvider/>
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
